routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'UserController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout');

Route::resource('user', 'UserController');
Route::get('pal', 'PokController@pal')->name('pal');
Route::get('pl', 'PokController@pel')->name('pel');
Route::get('doc/{id}', 'PokController@doc')->name('doc');
Route::get('cetak-pdf/{id}', 'PokController@cetakPdf')->name('pdf');
Route::get('preview-pdf/{id}', 'PokController@previewPdf')->name('preview');
Route::post('import', 'PokController@import')->name('import');
Route::resource('pok', 'PokController');
Route::resource('penyedia', 'PenyediaController');

resources/views/layout/breadcrumb.blade.php
<!-- Content Header (Page header) -->
<section class="content-header">
	  @if(isset($title))
  <h1>{{ ucwords(str_replace('-',' ', $title)) }}</h1>
  @else
  <h1>{{ (isset($page)) ? ucwords(str_replace('-',' ', $page)) : 'Dashboard' }}</h1>
  @endif
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">{{ (isset($page)) ? ucwords($page) : 'Dashboard' }}</li>
  </ol>
</section>

resources/views/layout/css-global.blade.php
<link rel="stylesheet" type="text/css" href="{{ asset('lte') }}/css/component.css" />
<link rel="stylesheet" href="{{asset('lte/bower_components')}}/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('lte/bower_components')}}/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{asset('lte/bower_components')}}/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('lte')}}/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{asset('lte')}}/css/skins/_all-skins.min.css">

  @include('layout.css-local')

  <link rel="stylesheet" href="{{ asset('lte') }}/css/custom.css?v=0.4">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/layout/css-local.blade.php
@if(isset($localAsset))
	@foreach($localAsset as $key => $val)
		@includeIf('util.css.'.$val)
	@endforeach
@endif

@includeIf($local_css_path.$page)

resources/views/layout/footer.blade.php
<footer class="main-footer">
	<div class="pull-right hidden-xs">
	  <b>Version</b> 2.4.0
	</div>
	<strong>Copyright &copy; 2019</strong> 
	All rights reserved.
</footer>

resources/views/layout/header.blade.php
<header class="main-header" style="background-color:#fff">
    <!-- Logo -->
    <a class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">
        `<img src="{{asset('lte/img')}}/logo.jpeg" style="width:45px" />  
      </span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">
      `<img src="{{asset('lte/img')}}/logo.jpeg" style="width:45px" />
      </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <h4 style="float:left;margin-top:15px">Sistem Informasi Administrasi Pengadaan</h4>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can bepside found in dropdown.less -->
          <li class="dropdown user user-menu" style="background-color:#dd4b39">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs">{{$user['name']}}</span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{{route('user.edit', ['id' => Auth::id()])}}?type=profile" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{{url('/logout')}}" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

resources/views/layout/js-global.blade.php
<!-- jQuery 3 -->
<script src="{{asset('lte/bower_components')}}/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('lte/bower_components')}}/jquery-ui/jquery-ui.min.js"></script>

<!-- Bootstrap 3.3.7 -->
<script src="{{asset('lte/bower_components')}}/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- AdminLTE App -->
<script src="{{asset('lte')}}/js/adminlte.min.js"></script>

<script src="{{ asset('lte') }}/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="{{ asset('lte') }}/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script src="{{ asset('lte') }}//js/custom-file-input.js"></script>

<script>
  $(function () {
    $('#example1').DataTable({
    	"order":[[0, 'desc']]
    })
  })
</script>

@include('layout.js-local')

resources/views/layout/js-local.blade.php
@if(isset($localAsset))
	@foreach($localAsset as $key => $val)
		@includeIf('util.js.'.$val)
	@endforeach
@endif

@includeIf($local_js_path.$page)

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html>
  <head>

    <!-- META -->
    @include("layout.meta")

    <!-- CSS -->
    @include("layout.css-global")

  </head>
  <body class="hold-transition skin-white sidebar-mini">
    <div class="wrapper">

      <!-- HEADER -->
      @include("layout.header")

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">

        <!-- SIDEBAR -->
        @include("layout.sidebar")    

        @yield("content")
        <div style="clear: both;"></div>
      
      </div>

      <!-- SIDEBAR -->
      @include("layout.footer")    

    </div>

    <!-- SIDEBAR -->
    @include("layout.js-global")      

  </body>
</html>

resources/views/layout/meta.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>SIAPLOGISTIKBIN</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

resources/views/layout/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
          <li @if($page == 'user') class="active" @endif>
            <a href="{{route('user.index')}}">
            <i class="fa fa-users"></i> <span>Home</span>
            </a>
          </li>

          <li @if($page == 'pok') class="active" @endif>
            <a href="{{route('pok.index')}}">
            <i class="fa fa-newspaper-o"></i> <span>List POK</span>
            </a>
          </li>

          <li @if($page == 'pok') class="active" @endif>
            <a href="{{route('pok.create')}}">
            <i class="fa fa-newspaper-o"></i> <span>POK</span>
            </a>
          </li>

          <li @if($page == 'pl') class="active" @endif>
            <a href="{{route('pel')}}">
            <i class="fa fa-newspaper-o"></i> <span>PL</span>
            </a>
          </li>

          <li @if($page == 'pal') class="active" @endif>
            <a href="{{route('pal')}}">
            <i class="fa fa-newspaper-o"></i> <span>PAL</span>
            </a>
          </li>

          <li @if($page == 'penyedia') class="active" @endif>
            <a href="{{route('penyedia.index')}}">
            <i class="fa fa-newspaper-o"></i> <span>Daftar Penyedia</span>
            </a>
          </li>
          
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>